server:
  port: 8082

spring:
  application:
    name: cache-service
#  cloud:
#    nacos:
#      #      config:
#      #        server-addr: localhost:8848
#      discovery:
#        #      server-addr: 47.112.148.78:8848
#        server-addr: 39.105.36.4:8848
#        file-extension: yaml #这里我们获取的yaml格式的配置

  #配置redis
  redis:
#    host: localhost
    host: 39.105.36.4
    port: 6379
    database: 0

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 600000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的实际
  ConnectTimeout: 600000

