server:
  port: 8083
spring:
  application:
    name: search-service
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
  #  配置es
  elasticsearch:
    jest:
#      uris: http://192.168.177.102:9200
      uris: http://47.112.148.78:9200
#    rest:
#      uris: http://192.168.177.102:9200
#      username: es
#      password: es


#    jest:
#      uris:


#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 600000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的实际
  ConnectTimeout: 600000

