server:
  port: 8084

spring:
  application:
    name: recommender-server
#  cloud:
#    nacos:
#      config:
#        server-addr: localhost:8848
  data:
    mongodb:
#      host: localhost
      host: 39.105.36.4
      database: recommender
      port: 27017
#      username: admin
#      password: admin

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 600000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的实际
  ConnectTimeout: 600000