server:
  port: 8086

#日志级别
#logging:
#  level:
#    root=info
spring:
  application:
    name: back-system
  thymeleaf:
    cache: false # 关闭thymeleaf的缓存(热部署)
    mode: LEGACYHTML5 # 松校验
  cloud:
    nacos:
#      config:
#        server-addr: http://47.112.148.78:8848
#        server-addr: 47.112.148.78:8848
      discovery:
        server-addr: 47.112.148.78:8848
        file-extension: yaml #这里我们获取的yaml格式的配置

  mvc:
    static-path-pattern: /**

ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 600000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的实际
  ConnectTimeout: 600000
